apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-db
  labels:
    name: session-db
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: session-db
  template:
    metadata:
      labels:
        name: session-db
      annotations:
        prometheus.io.scrape: "false"
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: session-db
          image: redis:7-alpine
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          securityContext:
            runAsUser: 999
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /data
              name: sesion-db-vol
      volumes:
        - name: sesion-db-vol
          emptyDir:
            medium: Memory
      nodeSelector:
        node-role.kubernetes.io/worker: ""
