apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: sock-shop
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: user-db
  template:
    metadata:
      labels:
        name: user-db
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: user-db
          image: quay.io/powercloud/sock-shop-user-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
          securityContext:
            runAsUser: 999
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /data/db-users
              name: users-db-vol
            - mountPath: /tmp
              name: users-db-temp-vol
      volumes:
        - name: users-db-vol
          persistentVolumeClaim:
            claimName: user-db-temp-pvc
        - name: users-db-temp-vol
          emptyDir: {}
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/arch: amd64
